### ISSUE TITLE
Will it can edit the resources.assets ?

### ISSUE THREAD

**Issue by zhangzhi0000** [Chlorie/Deenote#3]
In Deemo 3.1 the Unity Asset Editor can`t open the resources.assets.Because of the large file.Can you help me? (Now I play it in Deemo 2.1.1 with iOS). 
Well,Thank you very much.

**Comment by Chlorie** [comment]
UAE works perfect for me when editing assets from Deemo 3.1 so I don't know what's the problem on your side.
For the feature request, I'm not planning to do that in the near future so sorry about that.

**Comment by zhangzhi0000** [comment]
So can you tell me about your computer configuration ? 
My computer :
Intel i3-6100 
Kingston DDR4 2133MHz 12GB
Win7 SP1 Ultimate 

Eh..  it seems that require more than 16GB RAM .

**Comment by Chlorie** [comment]
No it isn't. My computer has only 8GB RAM.

**Comment by Chlorie** [comment]
Oh, by the way I recommend UnityEX if that's still a problem for you
