### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by Gennadiyev** [Chlorie/Deenote#4]
When creating a project using an mp3 and location selected to be C:\Deenote-charts, with project name `Drop - Granat`.
error.log
[error.log](https://github.com/Chlorie/Deenote/files/1715989/error.log/)
crash.dmp: (please manually change the file name)
[crash.txt](https://github.com/Chlorie/Deenote/files/1715990/crash.txt)

**Comment by Chlorie** [comment]
It seems that on some devices the NAudio part doesn't work (vorbis.acm caused an Access Violation). That's a known bug, but I don't know the cause of that bug. Someone said that changing to the 32-bit version of Deenote and it would work properly.
So please try the 32-bit version, but if even that can't solve the problem I still can't do anything to solve this problem. Maybe I'll change the library I use but not in the near future...
Anyway thanks for reporting this issue to me. Hope your problem will be solved.

**Comment by Gennadiyev** [comment]
Thanks a lot for your explanation! I read a bit of the code actually and found the fact out hours ago tho.. **Best wishes to Deenote!**

**Comment by Chlorie** [comment]
Found out the fact? I'm really curious now... Have you found out the problem and got the solution to that?
