### ISSUE TITLE
无法填充拍线？

### ISSUE THREAD

**Issue by ajcxsu** [Chlorie/Deenote#6]
![qq 20180608100421](https://user-images.githubusercontent.com/31349569/41135277-6c898aea-6b03-11e8-853b-0ffdc5e7e9e9.png)
0.7.1版本尝试填充拍线，重启过多次
但并没有任何作用...

**Comment by Z-fly** [comment]
第一次尝试自制吗？如果你有其他音游自制经历应该不难理解。
我简单说下，乐理方面如有不对请指盐酸指正。

拍线指的是指音乐的节拍，由音乐的BPM控制。
然而你并没有设置**横向格线**。
![](https://user-images.githubusercontent.com/10470892/41137638-c9b8b2b2-6b0e-11e8-841f-9212a09ade39.jpg)

**Comment by ajcxsu** [comment]
@Z-fly 
是第一次自制，其他音游自制经历只有osumania
真的非常感谢指导 qwq
